MyOrgViewer/Controllers/OrganizationController.cs
using DataAccessLayer;
using DataAccessLayer.IRepositories;
using DataAccessLayer.Repositories;
using MyOrgViewer.Models;
using MyOrgViewer.MyActionFilters;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyOrgViewer.Controllers
{
    public class OrganizationController : Controller
    {
        private IOrganizationRepository _organizationRepository;
        private IImageRepository _imageRepository;
        private IUserRepository _userRepository;
        private IOrgUserRepository _orgUserrepository;
        private IImageOrgRepository _orgImageRepository;
        private ITestRepository _testrep;
        public OrganizationController(IOrganizationRepository orgRepository, IImageRepository imageRepository, IUserRepository userRepository, IOrgUserRepository orgUserrepository
            ,IImageOrgRepository orgImageRepository, ITestRepository testrep
            )
        {
            _organizationRepository = orgRepository;
            _imageRepository = imageRepository;
            _userRepository = userRepository;
            _orgUserrepository = orgUserrepository;
            _orgImageRepository = orgImageRepository;

            _testrep = testrep;
        }

        // GET: Organization
        public ActionResult Index()
        {
            OrgTitle model = new OrgTitle();
            model.Baslik = ConfigurationManager.AppSettings["OrgTitle"];
            model.AltBaslik = ConfigurationManager.AppSettings["OrgTitleAlt"];
            return View(model);
        }

        [ActionRight]
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [ActionRight]
        public ActionResult Add(Organization org)
        {
            if (Request.Files.Count <= 0)
            {
                ModelState.AddModelError("ImageValidation", "Image seçilmedir");
            }
            if (Request.Files[0].ContentLength<=0)
            {
                ModelState.AddModelError("ImageValidation", "Image seçilmedir");
            }


            if (!ModelState.IsValid)
            {
                return View(org);
            }

            Images image = new Images();
            image.imageUrl = Request.Files[0].FileName;
            _imageRepository.Add(image);

            var imagePath = ConfigurationManager.AppSettings["ImagePath"] + "/" + image.Id + "_" + image.imageUrl;

            Request.Files[0].SaveAs(imagePath);

            org.MainImageId = image.Id;
            org.Organizer = ((User)Session["User"]).Id;
          
            _organizationRepository.Add(org);
            
            return RedirectToAction("Index");
        }

        public PartialViewResult ListOrgs()
        {
            List<Organization> orgList = _organizationRepository.List();

            return PartialView(orgList);
        }


        [ActionRight]
        public ActionResult Detail(int id)
        {
            Organization model = _organizationRepository.Get(id);

            #region 1.way to get only not selected users
            ViewData["AllUsers"] = _userRepository.List().Where(c => !model.OrgUser.Any(x => x.UserId == c.Id)).ToList();
            #endregion

            #region  2.way to get only not selected users
            //List<User> tumUSer = _userRepository.List();
            //List<User> filteredUSer = new List<User>();
            //foreach (var usr in tumUSer)
            //{
            //    if(model.OrgUser.Where(c=>c.UserId==usr.Id).Count()<=0)
            //    {
            //        filteredUSer.Add(usr);
            //    }

            //}
            //ViewData["AllUsers"] = filteredUSer;
            #endregion

            return View(model);
        }

        public ActionResult AddMember(int selectedUser,int orgId)
        {
            OrgUser orgUser = new OrgUser();
            orgUser.OrgId = orgId;
            orgUser.UserId = selectedUser;
           
            _orgUserrepository.Add(orgUser);

            return RedirectToAction("Detail", new { id = orgId });
        }

        public ActionResult AddImage(int orgId)
        {
            Images img = new Images();
            img.imageUrl = Request.Files[0].FileName;
            _imageRepository.Add(img);

            string imagePath= ConfigurationManager.AppSettings["ImagePath"] + "/" + img.Id + "_" + img.imageUrl;

            Request.Files[0].SaveAs(imagePath);

            OrgImage orgimage = new OrgImage();
            orgimage.ImageId = img.Id;
            orgimage.OrgId = orgId;
            _orgImageRepository.Add(orgimage);


            return RedirectToAction("Detail", new { id = orgId });

        }

        public JsonResult deleteImage(int imageId)
        {
            OrgImage orgImage = _orgImageRepository.List().Where(c => c.ImageId == imageId).FirstOrDefault();

            _orgImageRepository.Delete(orgImage.Id);

            _imageRepository.Delete(imageId);

            return new JsonResult() { Data = "silindi çok pis" };
        }



        public ActionResult removeUser(int id,int orgId)
        {
            _orgUserrepository.Delete(id);


            return RedirectToAction("Detail", new { id = orgId });
        }

        public PartialViewResult MemberAdd()
        {
            return PartialView();
        }
    }
}

MyOrgViewer/Views/Organization/Add.cshtml
@model DataAccessLayer.Organization

@{
    ViewBag.Title = "Add";
}

<h2>Add</h2>

@using (Html.BeginForm("Add", "Organization", null, FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Organization</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.OrganizationDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.OrganizationDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.OrganizationDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Main Image", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="mainImage" id="mainImage" class="form-control" />
            @Html.ValidationMessage("ImageValidation", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MyOrgViewer/Views/Organization/Detail.cshtml
@model DataAccessLayer.Organization
<style>
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }

    td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #dddddd;
    }
</style>

@{
    ViewBag.Title = "Detail";
}

<h2>Detail</h2>

<div>
    <h4>Organization</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Image
        </dt>
        <dd>
            @{string imageUrl = "/Images/" + Model.Images.Id + "_" + Model.Images.imageUrl;}
            <img width="200" height="100" src="@imageUrl" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrganizationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrganizationDate)
        </dd>

    </dl>
</div>
<p>
    @using (Html.BeginForm("AddMember", "Organization", FormMethod.Post))
    {
        <input type="hidden" id="orgId" value="@Model.Id" name="orgId" />
        <div class="form-group">
            @Html.Label("USer", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @{ var UserList = (List<DataAccessLayer.User>)ViewData["AllUsers"]; }
                <select class="form-control" id="selectedUser" name="selectedUser">
                    @foreach (var item in UserList)
                    {
                        <option id="@item.Id" value="@item.Id">@item.Id  --  @item.UserName</option>
                    }

                </select>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add Participant" class="btn btn-default" />
            </div>
        </div>
    }

</p>
<div class="col-md-12" style="margin-bottom:50px">
    Katılımcılar
    <table>
        <tr>
            <th></th>
            <th>User</th>
        </tr>
        @foreach (var orguser in Model.OrgUser)
        {
            <tr>
                <td style="width: 22%;"> 
                    <a href="/Organization/removeUser/@orguser.Id?orgId=@Model.Id">delete</a>
                </td>
                <td>
                    @orguser.User.UserName
                </td>
            </tr>
        }
    </table>
</div>





<div class="col-md-12">

    @foreach (var orguser in Model.OrgImage)
    {
        string imagePath = "/Images" + "/" + orguser.Images.Id + "_" + orguser.Images.imageUrl;

        <div id="img_@orguser.Images.Id" class="col-md-4">
            <input type="button" id="btnDelete" name="btnDelete" value="Delete" onclick="deleteImage(@orguser.Images.Id)" />
            <img style="width:300px;height:200px" src='@imagePath' />
        </div>
    }

</div>

<p>
    @using (Html.BeginForm("AddImage", "Organization", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <input type="hidden" id="orgId" value="@Model.Id" name="orgId" />
        <div class="form-group">
            @Html.Label("Image", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="myFile" id="myFile" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add Image" class="btn btn-default" />
            </div>
        </div>
    }

</p>

<script>
    function deleteImage(erdal) {
        

        $.post("http://localhost:49263/Api/Values/" + erdal, { id: erdal }, function (message) {
            $('#img_' + erdal).remove();
            alert(message);
        });
    }


</script>

MyOrgViewer/Views/Organization/Index.cshtml
@model MyOrgViewer.Models.OrgTitle
@{
    ViewBag.Title = "Index";
}

<h2>@Model.Baslik</h2>
<h3>@Model.AltBaslik</h3>

@Html.ActionLink("Add New", "Add")

@*<h2>@ViewBag.baslik</h2>
    <h3>@ViewBag.altbaslik</h3>*@

<div id="orgList">
    @Html.Action("ListOrgs")
</div>

MyOrgViewer/Views/Organization/ListOrgs.cshtml
@model IEnumerable<DataAccessLayer.Organization>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrganizationDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OrganizationDate)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new {  id=item.Id  }) |
            @Html.ActionLink("Details", "Detail", new {  id=item.Id  }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>

MyOrgViewer/Views/Organization/MemberAdd.cshtml
@model DataAccessLayer.User

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>User</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>